#!/usr/bin/env bash
# ^^^shebang, very important to make sure it's exact

read -p "What year? [nnnn] " year
until [[ $year =~ [0-9]{4} ]]; do
    read -p "A year, please! [nnnn] " year
done
echo "Selected year: $year"